// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvwkdvpdmjagdbincqmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2d2tkdnBkbWphZ2RiaW5jcW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTI1MDAsImV4cCI6MjA3MTE2ODUwMH0.h-TgIiRzJWksdSmXPWZ1eGklLYe5yjJFaDda83VC_cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});